--------------------------------------------------------------------------------------
-- Name	       : OT (Oracle Tutorial) Sample Database
-- Link	       : http://www.oracletutorial.com/oracle-sample-database/
-- Version     : 1.0
-- Copyright   : Copyright © 2017 by www.oracletutorial.com. All Rights Reserved.
-- Notice      : Use this sample database for the educational purpose only.
--               Credit the site oracletutorial.com explitly in your materials that
--               use this sample database.
--------------------------------------------------------------------------------------


---------------------------------------------------------------------------
-- execute the following statements to create tables
---------------------------------------------------------------------------
-- region
CREATE TABLE region
  (
    region_id NUMBER GENERATED BY DEFAULT AS IDENTITY
    START WITH 5 PRIMARY KEY,
    region_name VARCHAR2( 50 ) NOT NULL
  );
-- country table
CREATE TABLE country
  (
    country_id   CHAR( 2 ) PRIMARY KEY  ,
    country_name VARCHAR2( 40 ) NOT NULL,
    region_id    NUMBER                 , -- fk
    CONSTRAINT fk_country_region FOREIGN KEY( region_id )
      REFERENCES region( region_id ) 
      ON DELETE CASCADE
  );

-- location
CREATE TABLE location
  (
    location_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 24 
                PRIMARY KEY       ,
    address     VARCHAR2( 255 ) NOT NULL,
    postal_code VARCHAR2( 20 )          ,
    city        VARCHAR2( 50 )          ,
    state       VARCHAR2( 50 )          ,
    country_id  CHAR( 2 )               , -- fk
    CONSTRAINT fk_location_country 
      FOREIGN KEY( country_id )
      REFERENCES country( country_id ) 
      ON DELETE CASCADE
  );
-- warehouse
CREATE TABLE warehouse
  (
    warehouse_id NUMBER 
                 GENERATED BY DEFAULT AS IDENTITY START WITH 10 
                 PRIMARY KEY,
    warehouse_name VARCHAR( 255 ) ,
    location_id    NUMBER( 12, 0 ), -- fk
    CONSTRAINT fk_warehouse_location 
      FOREIGN KEY( location_id )
      REFERENCES location( location_id ) 
      ON DELETE CASCADE
  );
-- employee
CREATE TABLE employee
  (
    employee_id NUMBER 
                GENERATED BY DEFAULT AS IDENTITY START WITH 108 
                PRIMARY KEY,
    first_name VARCHAR( 255 ) NOT NULL,
    last_name  VARCHAR( 255 ) NOT NULL,
    email      VARCHAR( 255 ) NOT NULL,
    phone      VARCHAR( 50 ) NOT NULL ,
    hire_date  DATE NOT NULL          ,
    manager_id NUMBER( 12, 0 )        , -- fk
    job_title  VARCHAR( 255 ) NOT NULL,
    CONSTRAINT fk_employee_manager 
        FOREIGN KEY( manager_id )
        REFERENCES employee( employee_id )
        ON DELETE CASCADE
  );
-- product category
CREATE TABLE product_category
  (
    category_id NUMBER 
                GENERATED BY DEFAULT AS IDENTITY START WITH 6 
                PRIMARY KEY,
    category_name VARCHAR2( 255 ) NOT NULL
  );

-- product table
CREATE TABLE product
  (
    product_id NUMBER 
               GENERATED BY DEFAULT AS IDENTITY START WITH 289 
               PRIMARY KEY,
    product_name  VARCHAR2( 255 ) NOT NULL,
    description   VARCHAR2( 2000 )        ,
    standard_cost NUMBER( 9, 2 )          ,
    list_price    NUMBER( 9, 2 )          ,
    category_id   NUMBER NOT NULL         ,
    CONSTRAINT fk_product_category 
      FOREIGN KEY( category_id )
      REFERENCES product_category( category_id ) 
      ON DELETE CASCADE
  );
-- customer
CREATE TABLE customer
  (
    customer_id NUMBER 
                GENERATED BY DEFAULT AS IDENTITY START WITH 320 
                PRIMARY KEY,
    name         VARCHAR2( 255 ) NOT NULL,
    address      VARCHAR2( 255 )         ,
    website      VARCHAR2( 255 )         ,
    credit_limit NUMBER( 8, 2 )
  );
-- contact
CREATE TABLE contact
  (
    contact_id NUMBER 
               GENERATED BY DEFAULT AS IDENTITY START WITH 320 
               PRIMARY KEY,
    first_name  VARCHAR2( 255 ) NOT NULL,
    last_name   VARCHAR2( 255 ) NOT NULL,
    email       VARCHAR2( 255 ) NOT NULL,
    phone       VARCHAR2( 20 )          ,
    customer_id NUMBER                  ,
    CONSTRAINT fk_contact_customer 
      FOREIGN KEY( customer_id )
      REFERENCES customer( customer_id ) 
      ON DELETE CASCADE
  );
-- invoice table
CREATE TABLE invoice
  (
    invoice_id NUMBER 
             GENERATED BY DEFAULT AS IDENTITY START WITH 106 
             PRIMARY KEY,
    customer_id NUMBER( 6, 0 ) NOT NULL, -- fk
    status      VARCHAR( 20 ) NOT NULL ,
    salesman_id NUMBER( 6, 0 )         , -- fk
    invoice_date  DATE NOT NULL          ,
    CONSTRAINT fk_invoice_customer 
      FOREIGN KEY( customer_id )
      REFERENCES customer( customer_id )
      ON DELETE CASCADE,
    CONSTRAINT fk_invoice_employee 
      FOREIGN KEY( salesman_id )
      REFERENCES employee( employee_id ) 
      ON DELETE SET NULL
  );
-- invoice items
CREATE TABLE invoice_item
  (
    invoice_id   NUMBER( 12, 0 )                                , -- fk
    item_id    NUMBER( 12, 0 )                                ,
    product_id NUMBER( 12, 0 ) NOT NULL                       , -- fk
    quantity   NUMBER( 8, 2 ) NOT NULL                        ,
    unit_price NUMBER( 8, 2 ) NOT NULL                        ,
    CONSTRAINT pk_invoice_item 
      PRIMARY KEY( invoice_id, item_id ),
    CONSTRAINT fk_invoice_item_product 
      FOREIGN KEY( product_id )
      REFERENCES product( product_id ) 
      ON DELETE CASCADE,
    CONSTRAINT fk_invoice_item_invoice 
      FOREIGN KEY( invoice_id )
      REFERENCES invoice( invoice_id ) 
      ON DELETE CASCADE
  );
-- inventory
CREATE TABLE inventory
  (
    product_id   NUMBER( 12, 0 )        , -- fk
    warehouse_id NUMBER( 12, 0 )        , -- fk
    quantity     NUMBER( 8, 0 ) NOT NULL,
    CONSTRAINT pk_inventory 
      PRIMARY KEY( product_id, warehouse_id ),
    CONSTRAINT fk_inventory_product 
      FOREIGN KEY( product_id )
      REFERENCES product( product_id ) 
      ON DELETE CASCADE,
    CONSTRAINT fk_inventory_warehouse 
      FOREIGN KEY( warehouse_id )
      REFERENCES warehouse( warehouse_id ) 
      ON DELETE CASCADE
  );